# Generated by Django 2.2.3 on 2019-07-16 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_auto_20190323_0543'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='level',
            field=models.IntegerField(choices=[(1, 'user'), (2, 'admin'), (3, 'superuser')], default=1, verbose_name='회원등급'),
            preserve_default=False,
        ),
    ]
