# Generated by Django 2.2.3 on 2019-07-30 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0005_auto_20190716_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcuser',
            name='is_authenticated',
            field=models.BooleanField(default=False, verbose_name='인증여부'),
        ),
    ]
