# Generated by Django 2.2.3 on 2019-07-30 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0006_fcuser_is_authenticated'),
    ]

    operations = [
        migrations.CreateModel(
            name='FcuserValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashkey', models.CharField(max_length=256, verbose_name='인증키')),
                ('fcuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcuser.Fcuser')),
            ],
            options={
                'verbose_name': '패스트캠퍼스 사용자 인증키',
                'verbose_name_plural': '패스트 사용자 인증키',
                'db_table': 'fastcampus_fcuser_validation',
            },
        ),
    ]
