# Generated by Django 2.2.3 on 2019-07-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='like_cnt',
            field=models.IntegerField(default=0, verbose_name='좋아요 수'),
        ),
    ]
